spring:
  datasource:
    url: jdbc:h2:mem:orders
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:h2:mem:orders
    schemas: orders@localhost
    user: sa
    password: