spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb?useSSL=false
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mariadb://localhost:3306/testdb?useSSL=false
    user: root
    password:

  h2:
    console:
      enabled: true
